name: Scheduled Workflow
on:
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight UTC
    
jobs:
    daily-task:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2
            
            - name: Run daily task
              run: | 
                echo "This is a scheduled task running daily at midnight UTC"
                echo "Current date and time: $(date)"
                # Add any additional commands you want to run here